// Entry point for @sparkpack/visuals.
export type {
  VisualType,
  VisualConfigMap,
  QuestionVisualProps,
  QuestionRecord,
  AnswerStyle,
  NumberLineConfig,
  DiceConfig,
  CountObjectsConfig,
  ObjectArrayConfig,
  BarChartConfig,
  BarChartBar,
  BlockChartConfig,
  BlockChartRow,
  TallyChartConfig,
  TallyChartRow,
  ShapeGridConfig,
  ShapeClassifyConfig,
  CoinDisplayConfig,
  FractionOfSetConfig,
  SpinnerConfig,
  MatchingPairsConfig,
  ClockFaceConfig,
  WeightScaleConfig,
  WeightScaleItem,
  OptionFillConfig,
  OptionFillRow,
  MissingDigitsConfig,
  MissingDigitsSegment,
  CalculationChoicesConfig,
  ItemListConfig,
  NumberPatternConfig,
  NumberPatternEquationRow,
} from './types';
export { QuestionVisual } from './viewer/QuestionVisual';
export { QuestionContainer } from './viewer/QuestionContainer';
export { VisualizerDetails } from './viewer/VisualizerDetails';
export {
  NumberLine,
  Dice,
  CoinDisplay,
  MatchingPairs,
  BarChart,
  BlockChart,
  TallyChart,
  ObjectArray,
  FractionOfSet,
  Spinner,
  ShapeGrid,
  ShapeClassify,
  CountObjects,
  WeightScale,
  ClockFace,
  OptionFill,
  MissingDigits,
  CalculationChoices,
  ItemList,
  NumberPattern,
} from './renderers';
export {
  OBJECT_IDS,
  ObjectDrawing,
  isObjectInLibrary,
  type ObjectId,
} from './objects';
export {
  SHAPE_2D_IDS,
  SHAPE_3D_IDS,
  SHAPE_IDS,
  isShapeId,
  ShapeDrawing,
  getShapeRenderer,
  registerShapeRenderer,
  type ShapeId,
  type ShapeDrawingProps,
  type ShapeParams,
  type ParamsFor,
  type ShapeRenderOptions,
  type BBox,
  type ShapeRendererEntry,
} from './objects';
