/* Generated by scripts/generate-drawings.mjs - do not edit by hand */
/* eslint-disable @typescript-eslint/no-explicit-any */

import type { ReactNode } from 'react';
import type { ObjectId } from '../objectIds';

import tin_canSvg from './tin_can.svg?raw';
import cereal_boxSvg from './cereal_box.svg?raw';
import bagSvg from './bag.svg?raw';
import boxSvg from './box.svg?raw';
import party_hatSvg from './party_hat.svg?raw';
import balloonSvg from './balloon.svg?raw';
import cupcakeSvg from './cupcake.svg?raw';
import cookieSvg from './cookie.svg?raw';
import appleSvg from './apple.svg?raw';
import orangeSvg from './orange.svg?raw';
import bananaSvg from './banana.svg?raw';
import pearSvg from './pear.svg?raw';
import flowerSvg from './flower.svg?raw';
import sunSvg from './sun.svg?raw';
import moonSvg from './moon.svg?raw';
import cloudSvg from './cloud.svg?raw';
import treeSvg from './tree.svg?raw';
import duckSvg from './duck.svg?raw';
import birdSvg from './bird.svg?raw';
import fishSvg from './fish.svg?raw';
import catSvg from './cat.svg?raw';
import dogSvg from './dog.svg?raw';
import boatSvg from './boat.svg?raw';
import airplaneSvg from './airplane.svg?raw';
import toy_carSvg from './toy_car.svg?raw';
import bicycleSvg from './bicycle.svg?raw';
import chairSvg from './chair.svg?raw';
import cupSvg from './cup.svg?raw';
import bottleSvg from './bottle.svg?raw';
import bookSvg from './book.svg?raw';
import pencilSvg from './pencil.svg?raw';
import keySvg from './key.svg?raw';
import lockSvg from './lock.svg?raw';
import laptopSvg from './laptop.svg?raw';
import cameraSvg from './camera.svg?raw';
import clockSvg from './clock.svg?raw';
import lightbulbSvg from './lightbulb.svg?raw';
import guitarSvg from './guitar.svg?raw';
import envelopeSvg from './envelope.svg?raw';
import giftSvg from './gift.svg?raw';
import umbrellaSvg from './umbrella.svg?raw';
import flagSvg from './flag.svg?raw';
import buttonSvg from './button.svg?raw';
import houseSvg from './house.svg?raw';

const tin_canDataUrl = 'data:image/svg+xml,' + encodeURIComponent(tin_canSvg);
const cereal_boxDataUrl = 'data:image/svg+xml,' + encodeURIComponent(cereal_boxSvg);
const bagDataUrl = 'data:image/svg+xml,' + encodeURIComponent(bagSvg);
const boxDataUrl = 'data:image/svg+xml,' + encodeURIComponent(boxSvg);
const party_hatDataUrl = 'data:image/svg+xml,' + encodeURIComponent(party_hatSvg);
const balloonDataUrl = 'data:image/svg+xml,' + encodeURIComponent(balloonSvg);
const cupcakeDataUrl = 'data:image/svg+xml,' + encodeURIComponent(cupcakeSvg);
const cookieDataUrl = 'data:image/svg+xml,' + encodeURIComponent(cookieSvg);
const appleDataUrl = 'data:image/svg+xml,' + encodeURIComponent(appleSvg);
const orangeDataUrl = 'data:image/svg+xml,' + encodeURIComponent(orangeSvg);
const bananaDataUrl = 'data:image/svg+xml,' + encodeURIComponent(bananaSvg);
const pearDataUrl = 'data:image/svg+xml,' + encodeURIComponent(pearSvg);
const flowerDataUrl = 'data:image/svg+xml,' + encodeURIComponent(flowerSvg);
const sunDataUrl = 'data:image/svg+xml,' + encodeURIComponent(sunSvg);
const moonDataUrl = 'data:image/svg+xml,' + encodeURIComponent(moonSvg);
const cloudDataUrl = 'data:image/svg+xml,' + encodeURIComponent(cloudSvg);
const treeDataUrl = 'data:image/svg+xml,' + encodeURIComponent(treeSvg);
const duckDataUrl = 'data:image/svg+xml,' + encodeURIComponent(duckSvg);
const birdDataUrl = 'data:image/svg+xml,' + encodeURIComponent(birdSvg);
const fishDataUrl = 'data:image/svg+xml,' + encodeURIComponent(fishSvg);
const catDataUrl = 'data:image/svg+xml,' + encodeURIComponent(catSvg);
const dogDataUrl = 'data:image/svg+xml,' + encodeURIComponent(dogSvg);
const boatDataUrl = 'data:image/svg+xml,' + encodeURIComponent(boatSvg);
const airplaneDataUrl = 'data:image/svg+xml,' + encodeURIComponent(airplaneSvg);
const toy_carDataUrl = 'data:image/svg+xml,' + encodeURIComponent(toy_carSvg);
const bicycleDataUrl = 'data:image/svg+xml,' + encodeURIComponent(bicycleSvg);
const chairDataUrl = 'data:image/svg+xml,' + encodeURIComponent(chairSvg);
const cupDataUrl = 'data:image/svg+xml,' + encodeURIComponent(cupSvg);
const bottleDataUrl = 'data:image/svg+xml,' + encodeURIComponent(bottleSvg);
const bookDataUrl = 'data:image/svg+xml,' + encodeURIComponent(bookSvg);
const pencilDataUrl = 'data:image/svg+xml,' + encodeURIComponent(pencilSvg);
const keyDataUrl = 'data:image/svg+xml,' + encodeURIComponent(keySvg);
const lockDataUrl = 'data:image/svg+xml,' + encodeURIComponent(lockSvg);
const laptopDataUrl = 'data:image/svg+xml,' + encodeURIComponent(laptopSvg);
const cameraDataUrl = 'data:image/svg+xml,' + encodeURIComponent(cameraSvg);
const clockDataUrl = 'data:image/svg+xml,' + encodeURIComponent(clockSvg);
const lightbulbDataUrl = 'data:image/svg+xml,' + encodeURIComponent(lightbulbSvg);
const guitarDataUrl = 'data:image/svg+xml,' + encodeURIComponent(guitarSvg);
const envelopeDataUrl = 'data:image/svg+xml,' + encodeURIComponent(envelopeSvg);
const giftDataUrl = 'data:image/svg+xml,' + encodeURIComponent(giftSvg);
const umbrellaDataUrl = 'data:image/svg+xml,' + encodeURIComponent(umbrellaSvg);
const flagDataUrl = 'data:image/svg+xml,' + encodeURIComponent(flagSvg);
const buttonDataUrl = 'data:image/svg+xml,' + encodeURIComponent(buttonSvg);
const houseDataUrl = 'data:image/svg+xml,' + encodeURIComponent(houseSvg);

/** Map each object id that has an SVG to a drawing component. Missing ids (marble, strawberry, star, table, phone) have no drawing. */
export const DRAWINGS: Partial<Record<ObjectId, () => ReactNode>> = {
  tin_can: () => (
    <g>
      <image href={tin_canDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  cereal_box: () => (
    <g>
      <image href={cereal_boxDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  bag: () => (
    <g>
      <image href={bagDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  box: () => (
    <g>
      <image href={boxDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  party_hat: () => (
    <g>
      <image href={party_hatDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  balloon: () => (
    <g>
      <image href={balloonDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  cupcake: () => (
    <g>
      <image href={cupcakeDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  cookie: () => (
    <g>
      <image href={cookieDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  apple: () => (
    <g>
      <image href={appleDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  orange: () => (
    <g>
      <image href={orangeDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  banana: () => (
    <g>
      <image href={bananaDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  pear: () => (
    <g>
      <image href={pearDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  flower: () => (
    <g>
      <image href={flowerDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  sun: () => (
    <g>
      <image href={sunDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  moon: () => (
    <g>
      <image href={moonDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  cloud: () => (
    <g>
      <image href={cloudDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  tree: () => (
    <g>
      <image href={treeDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  duck: () => (
    <g>
      <image href={duckDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  bird: () => (
    <g>
      <image href={birdDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  fish: () => (
    <g>
      <image href={fishDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  cat: () => (
    <g>
      <image href={catDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  dog: () => (
    <g>
      <image href={dogDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  boat: () => (
    <g>
      <image href={boatDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  airplane: () => (
    <g>
      <image href={airplaneDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  toy_car: () => (
    <g>
      <image href={toy_carDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  bicycle: () => (
    <g>
      <image href={bicycleDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  chair: () => (
    <g>
      <image href={chairDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  cup: () => (
    <g>
      <image href={cupDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  bottle: () => (
    <g>
      <image href={bottleDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  book: () => (
    <g>
      <image href={bookDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  pencil: () => (
    <g>
      <image href={pencilDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  key: () => (
    <g>
      <image href={keyDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  lock: () => (
    <g>
      <image href={lockDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  laptop: () => (
    <g>
      <image href={laptopDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  camera: () => (
    <g>
      <image href={cameraDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  clock: () => (
    <g>
      <image href={clockDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  lightbulb: () => (
    <g>
      <image href={lightbulbDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  guitar: () => (
    <g>
      <image href={guitarDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  envelope: () => (
    <g>
      <image href={envelopeDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  gift: () => (
    <g>
      <image href={giftDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  umbrella: () => (
    <g>
      <image href={umbrellaDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  flag: () => (
    <g>
      <image href={flagDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  button: () => (
    <g>
      <image href={buttonDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
  house: () => (
    <g>
      <image href={houseDataUrl} x={-20} y={-20} width={40} height={40} preserveAspectRatio="xMidYMid meet" />
    </g>
  ),
};

/** Returns the SVG drawing for a library object id, or null if no SVG. */
export function getSvgDrawing(id: ObjectId): ReactNode {
  const fn = DRAWINGS[id];
  return fn ? fn() : null;
}

/** Object ids that have an SVG drawing in this module. */
export const OBJECT_IDS_WITH_DRAWINGS: ObjectId[] = ['tin_can', 'cereal_box', 'bag', 'box', 'party_hat', 'balloon', 'cupcake', 'cookie', 'apple', 'orange', 'banana', 'pear', 'flower', 'sun', 'moon', 'cloud', 'tree', 'duck', 'bird', 'fish', 'cat', 'dog', 'boat', 'airplane', 'toy_car', 'bicycle', 'chair', 'cup', 'bottle', 'book', 'pencil', 'key', 'lock', 'laptop', 'camera', 'clock', 'lightbulb', 'guitar', 'envelope', 'gift', 'umbrella', 'flag', 'button', 'house'];